// AUTO-GENERATED by kubejs-mcp. Do not edit manually.
// Re-applied on every add_recipe/remove_recipe. Game root reload via POST /api/reload/server.
ServerEvents.recipes((event) => {
  event.custom({"type":"meowaddons:mixing_t1","ingredients":[{"item":"minecraft:andesite"},{"item":"minecraft:andesite"}],"results":[{"id":"minecraft:diorite"}]});
  event.custom({"type":"meowaddons:mixing_t1","ingredients":[{"item":"2x minecraft:andesite"}],"results":[{"id":"minecraft:diorite"}]});
});
