# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
# Системный JAVA_HOME указывает на JDK 8, а moddev-плагину нужен 17+.
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-21.0.12.101-hotspot

# Mod
mod_id=meowrelics
mod_name=MeowRelics
mod_version=1.1.0
mod_group=meowrelics
mod_license=MIT

minecraft_version=1.21.1
neoforge_version=21.1.249
neoforge_loader_range=[21.1,)
minecraft_range=[1.21.1,1.21.2)