name = "Aqua SMP"
author = "Cacagd228"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba4d411ddbe279e98a4c0bab134bc98fb2cfab447c59e43a571dcbf363d0a53b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
