name = "Aqua SMP"
author = "Cacagd228"
version = "1.1.3-beta.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4fb743ea78558b502f6bf50e643091c0bdecdd60e9ed4e74ed0db4be3e380b0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
