name = "Aqua SMP"
author = "Cacagd228"
version = "1.1.7-release.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3d3dfcdb10d141ca1af3e1e5af9ede6463a3d913ee6b0883cfb315ac309ab18"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
