modLoader="kotlinforforge"
loaderVersion="[5,)"
license="MIT"
issueTrackerURL="https://github.com/Nanorasmus/HexJS/issues"

[[mods]]
modId="meowhex"
version="${version}"
displayName="MeowHex"
displayURL="https://github.com/Nanorasmus/HexJS"
logoFile="logo.png"
credits="Nanorasmus, petrak@, A1ex_Rom port, cacagd22811"
authors="cacagd22811"
description="Unified HexCasting mana fork + hex content (single NeoForge module, ex hexcasting+hex_js). Made and adapted for the Factory Must Meowing modpack"

[[mixins]]
config="hexplat.mixins.json"

[[mixins]]
config="hexcasting_forge.mixins.json"

[[mixins]]
config="meowhex.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.meowhex]]
modId="neoforge"
type="required"
versionRange="${neoforge_loader_range}"
ordering="NONE"
side="BOTH"

[[dependencies.meowhex]]
modId="minecraft"
type="required"
versionRange="${minecraft_range}"
ordering="NONE"
side="BOTH"

[[dependencies.meowhex]]
modId="paucal"
type="required"
versionRange="[0.7.0,0.8.0)"
ordering="NONE"
side="BOTH"

[[dependencies.meowhex]]
modId="patchouli"
type="required"
versionRange="[1.21.1-90,)"
ordering="NONE"
side="BOTH"

[[dependencies.meowhex]]
modId="caelus"
type="required"
versionRange="[7.0.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.meowhex]]
modId="curios"
type="optional"
versionRange="[9.5,)"
ordering="AFTER"
side="BOTH"

[[dependencies.meowhex]]
modId="jei"
type="optional"
versionRange="[19.21.2,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.meowhex]]
modId="create"
type="optional"
versionRange="[6.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.meowhex]]
modId="apothic_attributes"
type="optional"
versionRange="[2.10,)"
ordering="AFTER"
side="BOTH"

[[dependencies.meowhex]]
modId="placebo"
type="optional"
versionRange="[9.9,)"
ordering="AFTER"
side="BOTH"

[[dependencies.meowhex]]
modId="apofix"
type="optional"
versionRange="[1.0,)"
ordering="AFTER"
side="BOTH"
