modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="meowaddons"
version="1.0.0"
displayName="Meow Addons"
description="Interdimensional Transmitter"
authors="meowaddons"

[[dependencies.meowaddons]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.meowaddons]]
modId="create"
type="required"
versionRange="[6.0,)"
ordering="AFTER"
side="BOTH"
