package com.meowaddons;
import com.meowaddons.tier.Tier;
import com.meowaddons.tier.TieredCrushingWheelBlockEntity;
import com.meowaddons.tier.TieredCrushingWheelControllerBlockEntity;
import com.meowaddons.tier.TieredDeployerBlockEntity;
import com.meowaddons.tier.TieredMillstoneBlockEntity;
import com.meowaddons.tier.TieredMixerBlockEntity;
import com.meowaddons.tier.TieredPressBlockEntity;
import com.meowaddons.tier.TieredSawBlockEntity;
import com.meowaddons.transmitter.TransmitterBlockEntity;
import net.minecraft.core.registries.Registries;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;
public class ModBlockEntities {
 public static final DeferredRegister<BlockEntityType<?>> BLOCK_ENTITIES=DeferredRegister.create(Registries.BLOCK_ENTITY_TYPE,MeowAddons.MODID);
 public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TransmitterBlockEntity>> INTERDIMENSIONAL_TRANSMITTER=BLOCK_ENTITIES.register("interdimensional_transmitter",()->BlockEntityType.Builder.of(TransmitterBlockEntity::new,ModBlocks.INTERDIMENSIONAL_TRANSMITTER.get()).build(null));
 public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredPressBlockEntity>> TIERED_PRESS_T1=BLOCK_ENTITIES.register("press_t1",()->BlockEntityType.Builder.of((pos,state)->new TieredPressBlockEntity(pos,state,Tier.ANDESITE),ModBlocks.PRESS_T1.get()).build(null));
 public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredPressBlockEntity>> TIERED_PRESS_T2=BLOCK_ENTITIES.register("press_t2",()->BlockEntityType.Builder.of((pos,state)->new TieredPressBlockEntity(pos,state,Tier.BRASS),ModBlocks.PRESS_T2.get()).build(null));
 public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredPressBlockEntity>> TIERED_PRESS_T3=BLOCK_ENTITIES.register("press_t3",()->BlockEntityType.Builder.of((pos,state)->new TieredPressBlockEntity(pos,state,Tier.STEEL),ModBlocks.PRESS_T3.get()).build(null));
 public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredPressBlockEntity>> TIERED_PRESS_T4=BLOCK_ENTITIES.register("press_t4",()->BlockEntityType.Builder.of((pos,state)->new TieredPressBlockEntity(pos,state,Tier.SHADOW_STEEL),ModBlocks.PRESS_T4.get()).build(null));
 public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredPressBlockEntity>> TIERED_PRESS_T5=BLOCK_ENTITIES.register("press_t5",()->BlockEntityType.Builder.of((pos,state)->new TieredPressBlockEntity(pos,state,Tier.REFINED_RADIANCE),ModBlocks.PRESS_T5.get()).build(null));
 public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredPressBlockEntity>> TIERED_PRESS_T6=BLOCK_ENTITIES.register("press_t6",()->BlockEntityType.Builder.of((pos,state)->new TieredPressBlockEntity(pos,state,Tier.CHROMATIC),ModBlocks.PRESS_T6.get()).build(null));
 public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredCrushingWheelBlockEntity>> TIERED_CRUSHING_WHEEL_T1=BLOCK_ENTITIES.register("crushing_wheel_t1",()->BlockEntityType.Builder.of((pos,state)->new TieredCrushingWheelBlockEntity(pos,state,Tier.ANDESITE),ModBlocks.CRUSHING_WHEEL_T1.get()).build(null));
 public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredCrushingWheelBlockEntity>> TIERED_CRUSHING_WHEEL_T2=BLOCK_ENTITIES.register("crushing_wheel_t2",()->BlockEntityType.Builder.of((pos,state)->new TieredCrushingWheelBlockEntity(pos,state,Tier.BRASS),ModBlocks.CRUSHING_WHEEL_T2.get()).build(null));
 public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredCrushingWheelBlockEntity>> TIERED_CRUSHING_WHEEL_T3=BLOCK_ENTITIES.register("crushing_wheel_t3",()->BlockEntityType.Builder.of((pos,state)->new TieredCrushingWheelBlockEntity(pos,state,Tier.STEEL),ModBlocks.CRUSHING_WHEEL_T3.get()).build(null));
 public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredCrushingWheelBlockEntity>> TIERED_CRUSHING_WHEEL_T4=BLOCK_ENTITIES.register("crushing_wheel_t4",()->BlockEntityType.Builder.of((pos,state)->new TieredCrushingWheelBlockEntity(pos,state,Tier.SHADOW_STEEL),ModBlocks.CRUSHING_WHEEL_T4.get()).build(null));
 public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredCrushingWheelBlockEntity>> TIERED_CRUSHING_WHEEL_T5=BLOCK_ENTITIES.register("crushing_wheel_t5",()->BlockEntityType.Builder.of((pos,state)->new TieredCrushingWheelBlockEntity(pos,state,Tier.REFINED_RADIANCE),ModBlocks.CRUSHING_WHEEL_T5.get()).build(null));
 public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredCrushingWheelBlockEntity>> TIERED_CRUSHING_WHEEL_T6=BLOCK_ENTITIES.register("crushing_wheel_t6",()->BlockEntityType.Builder.of((pos,state)->new TieredCrushingWheelBlockEntity(pos,state,Tier.CHROMATIC),ModBlocks.CRUSHING_WHEEL_T6.get()).build(null));
 public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredMillstoneBlockEntity>> TIERED_MILLSTONE_T1=BLOCK_ENTITIES.register("millstone_t1",()->BlockEntityType.Builder.of((pos,state)->new TieredMillstoneBlockEntity(pos,state,Tier.ANDESITE),ModBlocks.MILLSTONE_T1.get()).build(null));
 public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredMillstoneBlockEntity>> TIERED_MILLSTONE_T2=BLOCK_ENTITIES.register("millstone_t2",()->BlockEntityType.Builder.of((pos,state)->new TieredMillstoneBlockEntity(pos,state,Tier.BRASS),ModBlocks.MILLSTONE_T2.get()).build(null));
 public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredMillstoneBlockEntity>> TIERED_MILLSTONE_T3=BLOCK_ENTITIES.register("millstone_t3",()->BlockEntityType.Builder.of((pos,state)->new TieredMillstoneBlockEntity(pos,state,Tier.STEEL),ModBlocks.MILLSTONE_T3.get()).build(null));
 public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredMillstoneBlockEntity>> TIERED_MILLSTONE_T4=BLOCK_ENTITIES.register("millstone_t4",()->BlockEntityType.Builder.of((pos,state)->new TieredMillstoneBlockEntity(pos,state,Tier.SHADOW_STEEL),ModBlocks.MILLSTONE_T4.get()).build(null));
 public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredMillstoneBlockEntity>> TIERED_MILLSTONE_T5=BLOCK_ENTITIES.register("millstone_t5",()->BlockEntityType.Builder.of((pos,state)->new TieredMillstoneBlockEntity(pos,state,Tier.REFINED_RADIANCE),ModBlocks.MILLSTONE_T5.get()).build(null));
 public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredMillstoneBlockEntity>> TIERED_MILLSTONE_T6=BLOCK_ENTITIES.register("millstone_t6",()->BlockEntityType.Builder.of((pos,state)->new TieredMillstoneBlockEntity(pos,state,Tier.CHROMATIC),ModBlocks.MILLSTONE_T6.get()).build(null));
 public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredMixerBlockEntity>> TIERED_MIXER_T1=BLOCK_ENTITIES.register("mixer_t1",()->BlockEntityType.Builder.of((pos,state)->new TieredMixerBlockEntity(pos,state,Tier.ANDESITE),ModBlocks.MIXER_T1.get()).build(null));
 public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredMixerBlockEntity>> TIERED_MIXER_T2=BLOCK_ENTITIES.register("mixer_t2",()->BlockEntityType.Builder.of((pos,state)->new TieredMixerBlockEntity(pos,state,Tier.BRASS),ModBlocks.MIXER_T2.get()).build(null));
 public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredMixerBlockEntity>> TIERED_MIXER_T3=BLOCK_ENTITIES.register("mixer_t3",()->BlockEntityType.Builder.of((pos,state)->new TieredMixerBlockEntity(pos,state,Tier.STEEL),ModBlocks.MIXER_T3.get()).build(null));
 public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredMixerBlockEntity>> TIERED_MIXER_T4=BLOCK_ENTITIES.register("mixer_t4",()->BlockEntityType.Builder.of((pos,state)->new TieredMixerBlockEntity(pos,state,Tier.SHADOW_STEEL),ModBlocks.MIXER_T4.get()).build(null));
 public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredMixerBlockEntity>> TIERED_MIXER_T5=BLOCK_ENTITIES.register("mixer_t5",()->BlockEntityType.Builder.of((pos,state)->new TieredMixerBlockEntity(pos,state,Tier.REFINED_RADIANCE),ModBlocks.MIXER_T5.get()).build(null));
 public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredMixerBlockEntity>> TIERED_MIXER_T6=BLOCK_ENTITIES.register("mixer_t6",()->BlockEntityType.Builder.of((pos,state)->new TieredMixerBlockEntity(pos,state,Tier.CHROMATIC),ModBlocks.MIXER_T6.get()).build(null));
 public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredSawBlockEntity>> TIERED_SAW_T1=BLOCK_ENTITIES.register("saw_t1",()->BlockEntityType.Builder.of((pos,state)->new TieredSawBlockEntity(pos,state,Tier.ANDESITE),ModBlocks.SAW_T1.get()).build(null));
 public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredSawBlockEntity>> TIERED_SAW_T2=BLOCK_ENTITIES.register("saw_t2",()->BlockEntityType.Builder.of((pos,state)->new TieredSawBlockEntity(pos,state,Tier.BRASS),ModBlocks.SAW_T2.get()).build(null));
 public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredSawBlockEntity>> TIERED_SAW_T3=BLOCK_ENTITIES.register("saw_t3",()->BlockEntityType.Builder.of((pos,state)->new TieredSawBlockEntity(pos,state,Tier.STEEL),ModBlocks.SAW_T3.get()).build(null));
 public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredSawBlockEntity>> TIERED_SAW_T4=BLOCK_ENTITIES.register("saw_t4",()->BlockEntityType.Builder.of((pos,state)->new TieredSawBlockEntity(pos,state,Tier.SHADOW_STEEL),ModBlocks.SAW_T4.get()).build(null));
 public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredSawBlockEntity>> TIERED_SAW_T5=BLOCK_ENTITIES.register("saw_t5",()->BlockEntityType.Builder.of((pos,state)->new TieredSawBlockEntity(pos,state,Tier.REFINED_RADIANCE),ModBlocks.SAW_T5.get()).build(null));
 public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredSawBlockEntity>> TIERED_SAW_T6=BLOCK_ENTITIES.register("saw_t6",()->BlockEntityType.Builder.of((pos,state)->new TieredSawBlockEntity(pos,state,Tier.CHROMATIC),ModBlocks.SAW_T6.get()).build(null));
  public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredCrushingWheelControllerBlockEntity>> TIERED_CRUSHING_WHEEL_CONTROLLER=BLOCK_ENTITIES.register("tiered_crushing_wheel_controller",()->BlockEntityType.Builder.of((pos,state)->new TieredCrushingWheelControllerBlockEntity(pos,state),ModBlocks.TIERED_CRUSHING_WHEEL_CONTROLLER.get()).build(null));
  public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredDeployerBlockEntity>> TIERED_DEPLOYER_T1=BLOCK_ENTITIES.register("deployer_t1",()->BlockEntityType.Builder.of((pos,state)->new TieredDeployerBlockEntity(pos,state,Tier.ANDESITE),ModBlocks.DEPLOYER_T1.get()).build(null));
  public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredDeployerBlockEntity>> TIERED_DEPLOYER_T2=BLOCK_ENTITIES.register("deployer_t2",()->BlockEntityType.Builder.of((pos,state)->new TieredDeployerBlockEntity(pos,state,Tier.BRASS),ModBlocks.DEPLOYER_T2.get()).build(null));
  public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredDeployerBlockEntity>> TIERED_DEPLOYER_T3=BLOCK_ENTITIES.register("deployer_t3",()->BlockEntityType.Builder.of((pos,state)->new TieredDeployerBlockEntity(pos,state,Tier.STEEL),ModBlocks.DEPLOYER_T3.get()).build(null));
  public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredDeployerBlockEntity>> TIERED_DEPLOYER_T4=BLOCK_ENTITIES.register("deployer_t4",()->BlockEntityType.Builder.of((pos,state)->new TieredDeployerBlockEntity(pos,state,Tier.SHADOW_STEEL),ModBlocks.DEPLOYER_T4.get()).build(null));
  public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredDeployerBlockEntity>> TIERED_DEPLOYER_T5=BLOCK_ENTITIES.register("deployer_t5",()->BlockEntityType.Builder.of((pos,state)->new TieredDeployerBlockEntity(pos,state,Tier.REFINED_RADIANCE),ModBlocks.DEPLOYER_T5.get()).build(null));
  public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<TieredDeployerBlockEntity>> TIERED_DEPLOYER_T6=BLOCK_ENTITIES.register("deployer_t6",()->BlockEntityType.Builder.of((pos,state)->new TieredDeployerBlockEntity(pos,state,Tier.CHROMATIC),ModBlocks.DEPLOYER_T6.get()).build(null));
  public static void register(IEventBus b){BLOCK_ENTITIES.register(b);}
}


