package com.meowaddons;
import com.meowaddons.block.FrameBlock;
import com.meowaddons.tier.Tier;
import com.meowaddons.tier.TieredPressBlock;
import com.meowaddons.tier.crusher.TieredCrusherBlock;
import com.meowaddons.tier.deployer.TieredDeployerBlock;
import com.meowaddons.tier.fan.TieredFanBlock;
import com.meowaddons.tier.millstone.TieredMillstoneBlock;
import com.meowaddons.tier.mixer.TieredMixerBlock;
import com.meowaddons.tier.saw.TieredSawBlock;
import com.meowaddons.transmitter.TransmitterBlock;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.material.MapColor;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.registries.DeferredRegister;
public class ModBlocks {
 public static final DeferredRegister.Blocks BLOCKS=DeferredRegister.createBlocks(MeowAddons.MODID);
 public static final DeferredBlock<TransmitterBlock> INTERDIMENSIONAL_TRANSMITTER=BLOCKS.register("interdimensional_transmitter",()->new TransmitterBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_GRAY).strength(2.0F).sound(SoundType.WOOD)));
 public static final DeferredBlock<FrameBlock> FRAME_ANDESITE=BLOCKS.register("frame_andesite",()->new FrameBlock(BlockBehaviour.Properties.of().mapColor(MapColor.STONE).strength(2.0F).sound(SoundType.STONE).noOcclusion().isViewBlocking((s,l,p)->false).isSuffocating((s,l,p)->false)));
 public static final DeferredBlock<FrameBlock> FRAME_STEEL=BLOCKS.register("frame_steel",()->new FrameBlock(BlockBehaviour.Properties.of().mapColor(MapColor.METAL).strength(3.0F).sound(SoundType.METAL).noOcclusion().isViewBlocking((s,l,p)->false).isSuffocating((s,l,p)->false)));
 public static final DeferredBlock<FrameBlock> FRAME_LATUN=BLOCKS.register("frame_latun",()->new FrameBlock(BlockBehaviour.Properties.of().mapColor(MapColor.GOLD).strength(2.5F).sound(SoundType.METAL).noOcclusion().isViewBlocking((s,l,p)->false).isSuffocating((s,l,p)->false)));
 public static final DeferredBlock<FrameBlock> FRAME_SHADOW_STEEL=BLOCKS.register("frame_shadow_steel",()->new FrameBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BLACK).strength(3.0F).sound(SoundType.METAL).noOcclusion().isViewBlocking((s,l,p)->false).isSuffocating((s,l,p)->false)));
 public static final DeferredBlock<FrameBlock> FRAME_REFINED_RADIANCE=BLOCKS.register("frame_refined_radiance",()->new FrameBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_YELLOW).strength(2.5F).sound(SoundType.METAL).noOcclusion().isViewBlocking((s,l,p)->false).isSuffocating((s,l,p)->false)));
 public static final DeferredBlock<FrameBlock> FRAME_CHROMATIC_COMPOUND=BLOCKS.register("frame_chromatic_compound",()->new FrameBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_PURPLE).strength(2.5F).sound(SoundType.METAL).noOcclusion().isViewBlocking((s,l,p)->false).isSuffocating((s,l,p)->false)));
 public static final DeferredBlock<TieredPressBlock> PRESS_T1=BLOCKS.register("press_t1",()->new TieredPressBlock(BlockBehaviour.Properties.of().mapColor(MapColor.STONE).strength(3.0F).sound(SoundType.METAL), Tier.ANDESITE));
 public static final DeferredBlock<TieredPressBlock> PRESS_T2=BLOCKS.register("press_t2",()->new TieredPressBlock(BlockBehaviour.Properties.of().mapColor(MapColor.GOLD).strength(3.0F).sound(SoundType.METAL), Tier.BRASS));
 public static final DeferredBlock<TieredPressBlock> PRESS_T3=BLOCKS.register("press_t3",()->new TieredPressBlock(BlockBehaviour.Properties.of().mapColor(MapColor.METAL).strength(3.5F).sound(SoundType.METAL), Tier.STEEL));
 public static final DeferredBlock<TieredPressBlock> PRESS_T4=BLOCKS.register("press_t4",()->new TieredPressBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BLACK).strength(4.0F).sound(SoundType.METAL), Tier.SHADOW_STEEL));
 public static final DeferredBlock<TieredPressBlock> PRESS_T5=BLOCKS.register("press_t5",()->new TieredPressBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_YELLOW).strength(4.0F).sound(SoundType.METAL), Tier.REFINED_RADIANCE));
 public static final DeferredBlock<TieredPressBlock> PRESS_T6=BLOCKS.register("press_t6",()->new TieredPressBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_PURPLE).strength(4.5F).sound(SoundType.METAL), Tier.CHROMATIC));
 public static final DeferredBlock<TieredMixerBlock> MIXER_T1=BLOCKS.register("mixer_t1",()->new TieredMixerBlock(BlockBehaviour.Properties.of().mapColor(MapColor.STONE).strength(3.0F).sound(SoundType.METAL), Tier.ANDESITE));
 public static final DeferredBlock<TieredMixerBlock> MIXER_T2=BLOCKS.register("mixer_t2",()->new TieredMixerBlock(BlockBehaviour.Properties.of().mapColor(MapColor.GOLD).strength(3.0F).sound(SoundType.METAL), Tier.BRASS));
 public static final DeferredBlock<TieredMixerBlock> MIXER_T3=BLOCKS.register("mixer_t3",()->new TieredMixerBlock(BlockBehaviour.Properties.of().mapColor(MapColor.METAL).strength(3.5F).sound(SoundType.METAL), Tier.STEEL));
 public static final DeferredBlock<TieredMixerBlock> MIXER_T4=BLOCKS.register("mixer_t4",()->new TieredMixerBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BLACK).strength(4.0F).sound(SoundType.METAL), Tier.SHADOW_STEEL));
 public static final DeferredBlock<TieredMixerBlock> MIXER_T5=BLOCKS.register("mixer_t5",()->new TieredMixerBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_YELLOW).strength(4.0F).sound(SoundType.METAL), Tier.REFINED_RADIANCE));
 public static final DeferredBlock<TieredMixerBlock> MIXER_T6=BLOCKS.register("mixer_t6",()->new TieredMixerBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_PURPLE).strength(4.5F).sound(SoundType.METAL), Tier.CHROMATIC));
 public static final DeferredBlock<TieredSawBlock> SAW_T1=BLOCKS.register("saw_t1",()->new TieredSawBlock(BlockBehaviour.Properties.of().mapColor(MapColor.STONE).strength(3.0F).sound(SoundType.METAL), Tier.ANDESITE));
 public static final DeferredBlock<TieredSawBlock> SAW_T2=BLOCKS.register("saw_t2",()->new TieredSawBlock(BlockBehaviour.Properties.of().mapColor(MapColor.GOLD).strength(3.0F).sound(SoundType.METAL), Tier.BRASS));
 public static final DeferredBlock<TieredSawBlock> SAW_T3=BLOCKS.register("saw_t3",()->new TieredSawBlock(BlockBehaviour.Properties.of().mapColor(MapColor.METAL).strength(3.5F).sound(SoundType.METAL), Tier.STEEL));
 public static final DeferredBlock<TieredSawBlock> SAW_T4=BLOCKS.register("saw_t4",()->new TieredSawBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BLACK).strength(4.0F).sound(SoundType.METAL), Tier.SHADOW_STEEL));
 public static final DeferredBlock<TieredSawBlock> SAW_T5=BLOCKS.register("saw_t5",()->new TieredSawBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_YELLOW).strength(4.0F).sound(SoundType.METAL), Tier.REFINED_RADIANCE));
 public static final DeferredBlock<TieredSawBlock> SAW_T6=BLOCKS.register("saw_t6",()->new TieredSawBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_PURPLE).strength(4.5F).sound(SoundType.METAL), Tier.CHROMATIC));
 public static final DeferredBlock<TieredMillstoneBlock> MILLSTONE_T1=BLOCKS.register("millstone_t1",()->new TieredMillstoneBlock(BlockBehaviour.Properties.of().mapColor(MapColor.STONE).strength(3.0F).sound(SoundType.METAL), Tier.ANDESITE));
 public static final DeferredBlock<TieredMillstoneBlock> MILLSTONE_T2=BLOCKS.register("millstone_t2",()->new TieredMillstoneBlock(BlockBehaviour.Properties.of().mapColor(MapColor.GOLD).strength(3.0F).sound(SoundType.METAL), Tier.BRASS));
 public static final DeferredBlock<TieredMillstoneBlock> MILLSTONE_T3=BLOCKS.register("millstone_t3",()->new TieredMillstoneBlock(BlockBehaviour.Properties.of().mapColor(MapColor.METAL).strength(3.5F).sound(SoundType.METAL), Tier.STEEL));
 public static final DeferredBlock<TieredMillstoneBlock> MILLSTONE_T4=BLOCKS.register("millstone_t4",()->new TieredMillstoneBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BLACK).strength(4.0F).sound(SoundType.METAL), Tier.SHADOW_STEEL));
 public static final DeferredBlock<TieredMillstoneBlock> MILLSTONE_T5=BLOCKS.register("millstone_t5",()->new TieredMillstoneBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_YELLOW).strength(4.0F).sound(SoundType.METAL), Tier.REFINED_RADIANCE));
 public static final DeferredBlock<TieredMillstoneBlock> MILLSTONE_T6=BLOCKS.register("millstone_t6",()->new TieredMillstoneBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_PURPLE).strength(4.5F).sound(SoundType.METAL), Tier.CHROMATIC));
 public static final DeferredBlock<TieredCrusherBlock> CRUSHER_T1=BLOCKS.register("crusher_t1",()->new TieredCrusherBlock(BlockBehaviour.Properties.of().mapColor(MapColor.STONE).strength(3.0F).sound(SoundType.METAL), Tier.ANDESITE));
 public static final DeferredBlock<TieredCrusherBlock> CRUSHER_T2=BLOCKS.register("crusher_t2",()->new TieredCrusherBlock(BlockBehaviour.Properties.of().mapColor(MapColor.GOLD).strength(3.0F).sound(SoundType.METAL), Tier.BRASS));
 public static final DeferredBlock<TieredCrusherBlock> CRUSHER_T3=BLOCKS.register("crusher_t3",()->new TieredCrusherBlock(BlockBehaviour.Properties.of().mapColor(MapColor.METAL).strength(3.5F).sound(SoundType.METAL), Tier.STEEL));
 public static final DeferredBlock<TieredCrusherBlock> CRUSHER_T4=BLOCKS.register("crusher_t4",()->new TieredCrusherBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BLACK).strength(4.0F).sound(SoundType.METAL), Tier.SHADOW_STEEL));
 public static final DeferredBlock<TieredCrusherBlock> CRUSHER_T5=BLOCKS.register("crusher_t5",()->new TieredCrusherBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_YELLOW).strength(4.0F).sound(SoundType.METAL), Tier.REFINED_RADIANCE));
 public static final DeferredBlock<TieredCrusherBlock> CRUSHER_T6=BLOCKS.register("crusher_t6",()->new TieredCrusherBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_PURPLE).strength(4.5F).sound(SoundType.METAL), Tier.CHROMATIC));
 public static final DeferredBlock<TieredDeployerBlock> DEPLOYER_T1=BLOCKS.register("deployer_t1",()->new TieredDeployerBlock(BlockBehaviour.Properties.of().mapColor(MapColor.STONE).strength(3.0F).sound(SoundType.METAL), Tier.ANDESITE));
 public static final DeferredBlock<TieredDeployerBlock> DEPLOYER_T2=BLOCKS.register("deployer_t2",()->new TieredDeployerBlock(BlockBehaviour.Properties.of().mapColor(MapColor.GOLD).strength(3.0F).sound(SoundType.METAL), Tier.BRASS));
 public static final DeferredBlock<TieredDeployerBlock> DEPLOYER_T3=BLOCKS.register("deployer_t3",()->new TieredDeployerBlock(BlockBehaviour.Properties.of().mapColor(MapColor.METAL).strength(3.5F).sound(SoundType.METAL), Tier.STEEL));
 public static final DeferredBlock<TieredDeployerBlock> DEPLOYER_T4=BLOCKS.register("deployer_t4",()->new TieredDeployerBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BLACK).strength(4.0F).sound(SoundType.METAL), Tier.SHADOW_STEEL));
 public static final DeferredBlock<TieredDeployerBlock> DEPLOYER_T5=BLOCKS.register("deployer_t5",()->new TieredDeployerBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_YELLOW).strength(4.0F).sound(SoundType.METAL), Tier.REFINED_RADIANCE));
 public static final DeferredBlock<TieredDeployerBlock> DEPLOYER_T6=BLOCKS.register("deployer_t6",()->new TieredDeployerBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_PURPLE).strength(4.5F).sound(SoundType.METAL), Tier.CHROMATIC));
 public static final DeferredBlock<TieredFanBlock> FAN_T1=BLOCKS.register("fan_t1",()->new TieredFanBlock(BlockBehaviour.Properties.of().mapColor(MapColor.STONE).strength(3.0F).sound(SoundType.METAL), Tier.ANDESITE));
 public static final DeferredBlock<TieredFanBlock> FAN_T2=BLOCKS.register("fan_t2",()->new TieredFanBlock(BlockBehaviour.Properties.of().mapColor(MapColor.GOLD).strength(3.0F).sound(SoundType.METAL), Tier.BRASS));
 public static final DeferredBlock<TieredFanBlock> FAN_T3=BLOCKS.register("fan_t3",()->new TieredFanBlock(BlockBehaviour.Properties.of().mapColor(MapColor.METAL).strength(3.5F).sound(SoundType.METAL), Tier.STEEL));
 public static final DeferredBlock<TieredFanBlock> FAN_T4=BLOCKS.register("fan_t4",()->new TieredFanBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BLACK).strength(4.0F).sound(SoundType.METAL), Tier.SHADOW_STEEL));
 public static final DeferredBlock<TieredFanBlock> FAN_T5=BLOCKS.register("fan_t5",()->new TieredFanBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_YELLOW).strength(4.0F).sound(SoundType.METAL), Tier.REFINED_RADIANCE));
 public static final DeferredBlock<TieredFanBlock> FAN_T6=BLOCKS.register("fan_t6",()->new TieredFanBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_PURPLE).strength(4.5F).sound(SoundType.METAL), Tier.CHROMATIC));
 public static void register(IEventBus b){BLOCKS.register(b);}
}
