package com.meowaddons;
import com.meowaddons.tier.Tier;
import com.meowaddons.tier.TieredCrushingWheelItem;
import com.meowaddons.tier.TieredDeployerItem;
import com.meowaddons.tier.TieredMillstoneItem;
import com.meowaddons.tier.TieredMixerItem;
import com.meowaddons.tier.TieredPressItem;
import com.meowaddons.tier.TieredSawItem;
import net.minecraft.world.item.BlockItem;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredRegister;
public class ModItems{
 public static final DeferredRegister.Items ITEMS=DeferredRegister.createItems(MeowAddons.MODID);
 public static final DeferredItem<BlockItem> INTERDIMENSIONAL_TRANSMITTER=ITEMS.registerSimpleBlockItem(ModBlocks.INTERDIMENSIONAL_TRANSMITTER);
 public static final DeferredItem<BlockItem> FRAME_ANDESITE=ITEMS.registerSimpleBlockItem(ModBlocks.FRAME_ANDESITE);
 public static final DeferredItem<BlockItem> FRAME_STEEL=ITEMS.registerSimpleBlockItem(ModBlocks.FRAME_STEEL);
 public static final DeferredItem<BlockItem> FRAME_LATUN=ITEMS.registerSimpleBlockItem(ModBlocks.FRAME_LATUN);
 public static final DeferredItem<BlockItem> FRAME_SHADOW_STEEL=ITEMS.registerSimpleBlockItem(ModBlocks.FRAME_SHADOW_STEEL);
 public static final DeferredItem<BlockItem> FRAME_REFINED_RADIANCE=ITEMS.registerSimpleBlockItem(ModBlocks.FRAME_REFINED_RADIANCE);
 public static final DeferredItem<BlockItem> FRAME_CHROMATIC_COMPOUND=ITEMS.registerSimpleBlockItem(ModBlocks.FRAME_CHROMATIC_COMPOUND);
 public static final DeferredItem<BlockItem> PRESS_T1=ITEMS.register("press_t1",()->new TieredPressItem(ModBlocks.PRESS_T1.get(), new net.minecraft.world.item.Item.Properties(), Tier.ANDESITE));
 public static final DeferredItem<BlockItem> PRESS_T2=ITEMS.register("press_t2",()->new TieredPressItem(ModBlocks.PRESS_T2.get(), new net.minecraft.world.item.Item.Properties(), Tier.BRASS));
 public static final DeferredItem<BlockItem> PRESS_T3=ITEMS.register("press_t3",()->new TieredPressItem(ModBlocks.PRESS_T3.get(), new net.minecraft.world.item.Item.Properties(), Tier.STEEL));
 public static final DeferredItem<BlockItem> PRESS_T4=ITEMS.register("press_t4",()->new TieredPressItem(ModBlocks.PRESS_T4.get(), new net.minecraft.world.item.Item.Properties(), Tier.SHADOW_STEEL));
 public static final DeferredItem<BlockItem> PRESS_T5=ITEMS.register("press_t5",()->new TieredPressItem(ModBlocks.PRESS_T5.get(), new net.minecraft.world.item.Item.Properties(), Tier.REFINED_RADIANCE));
 public static final DeferredItem<BlockItem> PRESS_T6=ITEMS.register("press_t6",()->new TieredPressItem(ModBlocks.PRESS_T6.get(), new net.minecraft.world.item.Item.Properties(), Tier.CHROMATIC));
 public static final DeferredItem<BlockItem> CRUSHING_WHEEL_T1=ITEMS.register("crushing_wheel_t1",()->new TieredCrushingWheelItem(ModBlocks.CRUSHING_WHEEL_T1.get(), new net.minecraft.world.item.Item.Properties(), Tier.ANDESITE));
 public static final DeferredItem<BlockItem> CRUSHING_WHEEL_T2=ITEMS.register("crushing_wheel_t2",()->new TieredCrushingWheelItem(ModBlocks.CRUSHING_WHEEL_T2.get(), new net.minecraft.world.item.Item.Properties(), Tier.BRASS));
 public static final DeferredItem<BlockItem> CRUSHING_WHEEL_T3=ITEMS.register("crushing_wheel_t3",()->new TieredCrushingWheelItem(ModBlocks.CRUSHING_WHEEL_T3.get(), new net.minecraft.world.item.Item.Properties(), Tier.STEEL));
 public static final DeferredItem<BlockItem> CRUSHING_WHEEL_T4=ITEMS.register("crushing_wheel_t4",()->new TieredCrushingWheelItem(ModBlocks.CRUSHING_WHEEL_T4.get(), new net.minecraft.world.item.Item.Properties(), Tier.SHADOW_STEEL));
 public static final DeferredItem<BlockItem> CRUSHING_WHEEL_T5=ITEMS.register("crushing_wheel_t5",()->new TieredCrushingWheelItem(ModBlocks.CRUSHING_WHEEL_T5.get(), new net.minecraft.world.item.Item.Properties(), Tier.REFINED_RADIANCE));
 public static final DeferredItem<BlockItem> CRUSHING_WHEEL_T6=ITEMS.register("crushing_wheel_t6",()->new TieredCrushingWheelItem(ModBlocks.CRUSHING_WHEEL_T6.get(), new net.minecraft.world.item.Item.Properties(), Tier.CHROMATIC));
 public static final DeferredItem<BlockItem> MILLSTONE_T1=ITEMS.register("millstone_t1",()->new TieredMillstoneItem(ModBlocks.MILLSTONE_T1.get(), new net.minecraft.world.item.Item.Properties(), Tier.ANDESITE));
 public static final DeferredItem<BlockItem> MILLSTONE_T2=ITEMS.register("millstone_t2",()->new TieredMillstoneItem(ModBlocks.MILLSTONE_T2.get(), new net.minecraft.world.item.Item.Properties(), Tier.BRASS));
 public static final DeferredItem<BlockItem> MILLSTONE_T3=ITEMS.register("millstone_t3",()->new TieredMillstoneItem(ModBlocks.MILLSTONE_T3.get(), new net.minecraft.world.item.Item.Properties(), Tier.STEEL));
 public static final DeferredItem<BlockItem> MILLSTONE_T4=ITEMS.register("millstone_t4",()->new TieredMillstoneItem(ModBlocks.MILLSTONE_T4.get(), new net.minecraft.world.item.Item.Properties(), Tier.SHADOW_STEEL));
 public static final DeferredItem<BlockItem> MILLSTONE_T5=ITEMS.register("millstone_t5",()->new TieredMillstoneItem(ModBlocks.MILLSTONE_T5.get(), new net.minecraft.world.item.Item.Properties(), Tier.REFINED_RADIANCE));
 public static final DeferredItem<BlockItem> MILLSTONE_T6=ITEMS.register("millstone_t6",()->new TieredMillstoneItem(ModBlocks.MILLSTONE_T6.get(), new net.minecraft.world.item.Item.Properties(), Tier.CHROMATIC));
 public static final DeferredItem<BlockItem> MIXER_T1=ITEMS.register("mixer_t1",()->new TieredMixerItem(ModBlocks.MIXER_T1.get(), new net.minecraft.world.item.Item.Properties(), Tier.ANDESITE));
 public static final DeferredItem<BlockItem> MIXER_T2=ITEMS.register("mixer_t2",()->new TieredMixerItem(ModBlocks.MIXER_T2.get(), new net.minecraft.world.item.Item.Properties(), Tier.BRASS));
 public static final DeferredItem<BlockItem> MIXER_T3=ITEMS.register("mixer_t3",()->new TieredMixerItem(ModBlocks.MIXER_T3.get(), new net.minecraft.world.item.Item.Properties(), Tier.STEEL));
 public static final DeferredItem<BlockItem> MIXER_T4=ITEMS.register("mixer_t4",()->new TieredMixerItem(ModBlocks.MIXER_T4.get(), new net.minecraft.world.item.Item.Properties(), Tier.SHADOW_STEEL));
 public static final DeferredItem<BlockItem> MIXER_T5=ITEMS.register("mixer_t5",()->new TieredMixerItem(ModBlocks.MIXER_T5.get(), new net.minecraft.world.item.Item.Properties(), Tier.REFINED_RADIANCE));
 public static final DeferredItem<BlockItem> MIXER_T6=ITEMS.register("mixer_t6",()->new TieredMixerItem(ModBlocks.MIXER_T6.get(), new net.minecraft.world.item.Item.Properties(), Tier.CHROMATIC));
 public static final DeferredItem<BlockItem> SAW_T1=ITEMS.register("saw_t1",()->new TieredSawItem(ModBlocks.SAW_T1.get(), new net.minecraft.world.item.Item.Properties(), Tier.ANDESITE));
 public static final DeferredItem<BlockItem> SAW_T2=ITEMS.register("saw_t2",()->new TieredSawItem(ModBlocks.SAW_T2.get(), new net.minecraft.world.item.Item.Properties(), Tier.BRASS));
 public static final DeferredItem<BlockItem> SAW_T3=ITEMS.register("saw_t3",()->new TieredSawItem(ModBlocks.SAW_T3.get(), new net.minecraft.world.item.Item.Properties(), Tier.STEEL));
 public static final DeferredItem<BlockItem> SAW_T4=ITEMS.register("saw_t4",()->new TieredSawItem(ModBlocks.SAW_T4.get(), new net.minecraft.world.item.Item.Properties(), Tier.SHADOW_STEEL));
 public static final DeferredItem<BlockItem> SAW_T5=ITEMS.register("saw_t5",()->new TieredSawItem(ModBlocks.SAW_T5.get(), new net.minecraft.world.item.Item.Properties(), Tier.REFINED_RADIANCE));
 public static final DeferredItem<BlockItem> SAW_T6=ITEMS.register("saw_t6",()->new TieredSawItem(ModBlocks.SAW_T6.get(), new net.minecraft.world.item.Item.Properties(), Tier.CHROMATIC));
 public static final DeferredItem<BlockItem> DEPLOYER_T1=ITEMS.register("deployer_t1",()->new TieredDeployerItem(ModBlocks.DEPLOYER_T1.get(), new net.minecraft.world.item.Item.Properties(), Tier.ANDESITE));
public static final DeferredItem<BlockItem> DEPLOYER_T2=ITEMS.register("deployer_t2",()->new TieredDeployerItem(ModBlocks.DEPLOYER_T2.get(), new net.minecraft.world.item.Item.Properties(), Tier.BRASS));
public static final DeferredItem<BlockItem> DEPLOYER_T3=ITEMS.register("deployer_t3",()->new TieredDeployerItem(ModBlocks.DEPLOYER_T3.get(), new net.minecraft.world.item.Item.Properties(), Tier.STEEL));
public static final DeferredItem<BlockItem> DEPLOYER_T4=ITEMS.register("deployer_t4",()->new TieredDeployerItem(ModBlocks.DEPLOYER_T4.get(), new net.minecraft.world.item.Item.Properties(), Tier.SHADOW_STEEL));
public static final DeferredItem<BlockItem> DEPLOYER_T5=ITEMS.register("deployer_t5",()->new TieredDeployerItem(ModBlocks.DEPLOYER_T5.get(), new net.minecraft.world.item.Item.Properties(), Tier.REFINED_RADIANCE));
public static final DeferredItem<BlockItem> DEPLOYER_T6=ITEMS.register("deployer_t6",()->new TieredDeployerItem(ModBlocks.DEPLOYER_T6.get(), new net.minecraft.world.item.Item.Properties(), Tier.CHROMATIC));
public static void register(IEventBus b){ITEMS.register(b);}
}
