modLoader = "javafml"
loaderVersion = "[4,)"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.21.2)"
ordering = "NONE"
side = "BOTH"

# MeowHex = порт Hex Casting (пакет at.petrak.hexcasting внутри)
[[dependencies.${mod_id}]]
modId = "meowhex"
type = "required"
versionRange = "[1.2.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "sable"
type = "required"
versionRange = "[2.0.0,3.0.0)"
ordering = "AFTER"
side = "BOTH"
