org.gradle.jvmargs=-Xmx3g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Basic Information
fileName=Apofix
modName=Apofix Attributes
modGroup=ru.apofix
modid=apofix
author=Apofix
desc=Addon attributes for Apothic Attributes: max mana, mana regen, mana discount, free cast chance, silence, magic resists (general, fire, water, earth, air).
version=1.0.0

# Dependencies
mcVersion=1.21.1
javaVersion=21
forgeVersion=21.1.235
parchmentVersion=2024.11.17-1.21.1
placeboVersion=9.9.0
attributeslibVersion=2.10.1

# Mixins
mixin=false
mixinVersion=0.8.7

# Publishing
releaseType=release
modLoaders=NeoForge
